# Generated by Django on 2026-05-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('seed_source', models.CharField(choices=[('HYBRID', 'Hybrid'), ('INBRED', 'Inbred'), ('OWN_SEED', 'Own Seed')], max_length=20)),
                ('variety', models.CharField(max_length=200)),
                ('harvest_area_ha', models.DecimalField(decimal_places=2, max_digits=8)),
                ('harvest_bags', models.PositiveIntegerField()),
                ('seed_bags_received', models.PositiveIntegerField(blank=True, null=True)),
                ('harvest_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encoded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_records_encoded', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-harvest_date', '-created_at'],
            },
        ),
    ]
