# Generated by Django 6.0.3 on 2026-05-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestrecord',
            name='moisture_content_pct',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='weight_type',
            field=models.CharField(choices=[('FRESH', 'Fresh / Wet'), ('DRIED', 'Dried')], default='FRESH', max_length=10),
        ),
    ]
