# Generated by Django 6.0.3 on 2026-06-09 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_harvestrecord_moisture_content_pct_and_more'),
        ('seed_poll', '0003_finalseed'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestrecord',
            name='poll',
            field=models.ForeignKey(blank=True, help_text='The season poll this harvest record belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='harvest_records', to='seed_poll.poll'),
        ),
    ]
