# Generated by Django 6.0.3 on 2026-06-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_harvestrecord_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvestrecord',
            name='moisture_content_pct',
        ),
        migrations.RemoveField(
            model_name='harvestrecord',
            name='weight_type',
        ),
    ]
