
from django.urls import path
from .views import (
    get_barangay_gis_data,
    FarmerSearchView,
    FarmerDistributionDetailView,
    DistributionEventListCreateView,
    DistributionEventDetailView,
    DistributionBatchListCreateView,
    DistributionBatchDetailView,
    DistributionBatchSubmitView,
    DistributionBatchSubmitDistributionView,
    DistributionBatchApproveView,
    DistributionBatchRejectView,
    DistributionBatchApproveDistributionView,
    DistributionBatchRejectDistributionView,
    DistributionBatchReopenView,
    DistributionBatchUnlockView,
    DistributionEntryCreateView,
    DistributionEntryDetailView,
    DistributionEntrySignatureView,
    DistributionEntryEncodeView,
    AdminPendingBatchesView,
    AdminDistributionPendingView,
    AdminDistributionStatsView,
    DistributionAuditView,
    BrgyDistributionContextView,
    FarmerHarvestContextView,
    AdminConfirmSeedDeliveryView,
    BrgyRequestDeleteEventView,
    AdminConfirmDeleteEventView,
)

urlpatterns = [

    # ── GIS MAP ──
    path('gis-data/',
         get_barangay_gis_data,
         name='gis-data'),

    # ── FARMER SEARCH ──
    path('farmers/search/',
         FarmerSearchView.as_view(),
         name='farmer-search'),
    path('farmers/<int:farmer_id>/distribution-detail/',
         FarmerDistributionDetailView.as_view(),
         name='farmer-distribution-detail'),

    # ── EVENTS ──
    path('events/',
         DistributionEventListCreateView.as_view(),
         name='event-list'),
    path('events/<int:pk>/',
         DistributionEventDetailView.as_view(),
         name='event-detail'),

    # ── BATCHES ──
    path('events/<int:event_id>/batches/',
         DistributionBatchListCreateView.as_view(),
         name='batch-list'),
    path('batches/<int:pk>/',
         DistributionBatchDetailView.as_view(),
         name='batch-detail'),
    path('batches/<int:pk>/submit/',
         DistributionBatchSubmitView.as_view(),
         name='batch-submit'),
    path('batches/<int:pk>/submit-distribution/',
         DistributionBatchSubmitDistributionView.as_view(),
         name='batch-submit-distribution'),
    path('batches/<int:pk>/approve/',
         DistributionBatchApproveView.as_view(),
         name='batch-approve'),
    path('batches/<int:pk>/reject/',
         DistributionBatchRejectView.as_view(),
         name='batch-reject'),
    path('batches/<int:pk>/distribution-approve/',
         DistributionBatchApproveDistributionView.as_view(),
         name='batch-distribution-approve'),
    path('batches/<int:pk>/distribution-reject/',
         DistributionBatchRejectDistributionView.as_view(),
         name='batch-distribution-reject'),
    path('batches/<int:pk>/reopen/',
         DistributionBatchReopenView.as_view(),
         name='batch-reopen'),
    path('batches/<int:pk>/unlock/',
         DistributionBatchUnlockView.as_view(),
         name='batch-unlock'),
    path('batches/<int:batch_id>/audit/',
         DistributionAuditView.as_view(),
         name='batch-audit'),

    # ── ENTRIES ──
    path('batches/<int:batch_id>/entries/',
         DistributionEntryCreateView.as_view(),
         name='entry-create'),
    path('entries/<int:pk>/',
         DistributionEntryDetailView.as_view(),
         name='entry-detail'),
    path('entries/<int:pk>/signature/',
         DistributionEntrySignatureView.as_view(),
         name='entry-signature'),
    path('entries/<int:pk>/encode-distribution/',
         DistributionEntryEncodeView.as_view(),
         name='entry-encode-distribution'),

     # ── BRGY CONTEXT ──
     path('brgy-context/',
     BrgyDistributionContextView.as_view(),
     name='brgy-context'),
     path('entries/farmer-harvest-context/',
     FarmerHarvestContextView.as_view(),
     name='farmer-harvest-context'),

    # ── ADMIN ──
    path('admin/pending/',
         AdminPendingBatchesView.as_view(),
         name='admin-pending'),
    path('admin/distribution-pending/',
         AdminDistributionPendingView.as_view(),
         name='admin-distribution-pending'),
    path('admin/stats/',
         AdminDistributionStatsView.as_view(),
         name='admin-stats'),
     path('events/<int:pk>/confirm-delivery/',
     AdminConfirmSeedDeliveryView.as_view(),
     name='confirm-delivery'),

     path('events/<int:pk>/request-delete/',
     BrgyRequestDeleteEventView.as_view(),
     name='event-request-delete'),
     path('events/<int:pk>/confirm-delete/',
     AdminConfirmDeleteEventView.as_view(),
     name='event-confirm-delete'),
]