# Generated by Django 6.0.3 on 2026-05-11 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0005_add_expected_sowing_authorized'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(choices=[('Abang', 'Abang'), ('Aliliw', 'Aliliw'), ('Atulinao', 'Atulinao'), ('Ayuti', 'Ayuti'), ('Igang', 'Igang'), ('Kabatete', 'Kabatete'), ('Kakawit', 'Kakawit'), ('Kalangay', 'Kalangay'), ('Kalyaat', 'Kalyaat'), ('Kilib', 'Kilib'), ('Kulapi', 'Kulapi'), ('Mahabang Parang', 'Mahabang Parang'), ('Malupak', 'Malupak'), ('Manasa', 'Manasa'), ('May-It', 'May-It'), ('Nagsinamo', 'Nagsinamo'), ('Nalunao', 'Nalunao'), ('Palola', 'Palola'), ('Piis', 'Piis'), ('Samil', 'Samil'), ('Tiawe', 'Tiawe'), ('Tinamnan', 'Tinamnan')], max_length=50)),
                ('phase', models.CharField(choices=[('DISTRIBUTED', 'Seed Distributed'), ('ESTABLISHED', 'Crop Established'), ('TILLERING', 'Tillering'), ('FLOWERING', 'Flowering'), ('RIPENING', 'Ripening'), ('HARVESTING', 'Harvesting')], max_length=15)),
                ('date_observed', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('area_monitored', models.DecimalField(decimal_places=2, help_text='Area monitored in hectares', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distribution_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_monitoring_records', to='distribution.distributionentry')),
                ('encoded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crop_monitoring_encoded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crop Monitoring Record',
                'verbose_name_plural': 'Crop Monitoring Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
