# Generated by Django 6.0.3 on 2026-05-11 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayCropSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(max_length=100, unique=True)),
                ('dominant_phase', models.CharField(choices=[('DISTRIBUTION', 'Seed Distribution'), ('ESTABLISHMENT', 'Crop Establishment'), ('TILLERING', 'Tillering'), ('FLOWERING', 'Flowering'), ('RIPENING', 'Ripening'), ('HARVESTING', 'Harvesting')], default='DISTRIBUTION', max_length=20)),
                ('total_farmers', models.PositiveIntegerField(default=0)),
                ('distribution_count', models.PositiveIntegerField(default=0)),
                ('establishment_count', models.PositiveIntegerField(default=0)),
                ('tillering_count', models.PositiveIntegerField(default=0)),
                ('flowering_count', models.PositiveIntegerField(default=0)),
                ('ripening_count', models.PositiveIntegerField(default=0)),
                ('harvesting_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barangay Crop Summary',
                'verbose_name_plural': 'Barangay Crop Summaries',
                'ordering': ['barangay'],
            },
        ),
        migrations.CreateModel(
            name='CropMonitoringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(max_length=100)),
                ('crop_phase', models.CharField(choices=[('DISTRIBUTION', 'Seed Distribution'), ('ESTABLISHMENT', 'Crop Establishment'), ('TILLERING', 'Tillering'), ('FLOWERING', 'Flowering'), ('RIPENING', 'Ripening'), ('HARVESTING', 'Harvesting')], max_length=20)),
                ('crop_establishment', models.CharField(blank=True, choices=[('DS', 'Direct Seeding (D)'), ('TP', 'Transplanting (T)')], help_text='Only required if phase is ESTABLISHMENT', max_length=2, null=True)),
                ('area_monitored_ha', models.DecimalField(blank=True, decimal_places=2, help_text='Area actually monitored in hectares', max_digits=6, null=True)),
                ('sowing_date', models.DateField(blank=True, help_text='Date when planting/sowing started', null=True)),
                ('variety_name', models.CharField(blank=True, help_text='Crop variety observed in the field', max_length=100)),
                ('remarks', models.TextField(blank=True, help_text='AT field observations, issues, or notes')),
                ('date_observed', models.DateField()),
                ('encoded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encoded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_encoded', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_monitoring_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crop Monitoring Record',
                'ordering': ['-date_observed', '-encoded_at'],
            },
        ),
        migrations.DeleteModel(
            name='CropMonitoring',
        ),
    ]
