# Generated by Django 6.0.3 on 2026-05-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_monitoring', '0003_add_phase_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropmonitoringrecord',
            name='seed_source',
            field=models.CharField(blank=True, choices=[('HYBRID', 'Hybrid Seed'), ('INBRED', 'Inbred Seed'), ('OWN_SEED', 'Own Seed')], help_text='Source of seed used by the farmer for this observation', max_length=10, null=True),
        ),
    ]
