# Generated by Django 6.0.3 on 2026-06-03 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_monitoring', '0004_cropmonitoringrecord_seed_source'),
        ('seed_poll', '0003_finalseed'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangaycropsummary',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_summaries', to='seed_poll.poll'),
        ),
        migrations.AddField(
            model_name='cropmonitoringrecord',
            name='poll',
            field=models.ForeignKey(blank=True, help_text='Season poll this record belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_monitoring_records', to='seed_poll.poll'),
        ),
        migrations.AlterField(
            model_name='barangaycropsummary',
            name='barangay',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='barangaycropsummary',
            unique_together={('poll', 'barangay')},
        ),
    ]
