# Generated by Django 6.0.3 on 2026-04-08 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seed_poll', '0002_alter_seedtype_options_alter_pollvote_hybrid_choice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(max_length=100)),
                ('intervention', models.CharField(choices=[('RCEF', 'RCEF (Rice Competitiveness Enhancement Fund)'), ('NRP', 'NRP (National Rice Program)'), ('RFO', 'RFO (Regional Field Office)'), ('OTHER', 'Other')], max_length=10)),
                ('season', models.CharField(choices=[('WET', 'Wet Season'), ('DRY', 'Dry Season')], max_length=3)),
                ('year', models.PositiveIntegerField()),
                ('organization_name', models.CharField(help_text='Name of farmer association or organization', max_length=200)),
                ('total_members', models.PositiveIntegerField(help_text='Expected total number of farmers in this event')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_events_created', to=settings.AUTH_USER_MODEL)),
                ('seed_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_events', to='seed_poll.seedtype')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_events', to='seed_poll.seedvariety')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.PositiveIntegerField(help_text='Auto-incremented per event: 1, 2, 3...')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_approved', to=settings.AUTH_USER_MODEL)),
                ('encoded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_encoded', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='distribution.distributionevent')),
            ],
            options={
                'ordering': ['batch_number'],
                'unique_together': {('event', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='DistributionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Event Created'), ('ENCODED', 'Farmer Encoded'), ('SIGNED', 'Signature Captured'), ('SUBMITTED', 'Batch Submitted'), ('APPROVED', 'Batch Approved'), ('REJECTED', 'Batch Rejected'), ('EDITED', 'Entry Edited'), ('LOCKED', 'Batch Re-locked after Edit')], max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='distribution.distributionbatch')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='distribution.distributionevent')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DistributionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(help_text='Position in the batch: 1 to 10')),
                ('farm_area_ha', models.DecimalField(blank=True, decimal_places=2, help_text='Farm area in hectares', max_digits=6, null=True)),
                ('crop_establishment', models.CharField(blank=True, choices=[('DS', 'Direct Seeding'), ('TP', 'Transplanting')], max_length=2, null=True)),
                ('qty_bags', models.PositiveIntegerField(blank=True, help_text='Number of seed bags received', null=True)),
                ('date_received', models.DateField(blank=True, help_text='Date when farmer received seeds', null=True)),
                ('area_planted', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('expected_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('signature', models.TextField(blank=True, default='', help_text='Base64 PNG of farmer e-signature/thumbmark')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('encoded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='distribution.distributionbatch')),
                ('encoded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_encoded', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['row_number'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'farmer'), name='unique_farmer_per_batch'), models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_row_per_batch')],
            },
        ),
    ]
