# Generated by Django 6.0.3 on 2026-04-09 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionevent',
            name='seed_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributionevent',
            name='seed_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionevent',
            name='seed_delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_deliveries_confirmed', to=settings.AUTH_USER_MODEL),
        ),
    ]
