# Generated by Django 6.0.3 on 2026-04-11 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_distributionevent_seed_delivered_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionevent',
            name='delete_request_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='distributionevent',
            name='delete_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributionevent',
            name='delete_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionevent',
            name='delete_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delete_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
