# Generated by Django on 2026-04-11
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_distributionevent_delete_request_note_and_more'),
        ('seed_poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionentry',
            name='variety',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='distribution_entries',
                to='seed_poll.seedvariety'
            ),
        ),
        migrations.AddField(
            model_name='distributionentry',
            name='data_sharing',
            field=models.BooleanField(
                default=False,
                help_text='Farmer agreed to data sharing with PhilRice'
            ),
        ),
    ]
