# Generated by GitHub Copilot
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_add_entry_variety_data_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionentry',
            name='expected_sowing_date',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Expected sowing date (e.g. June/2nd Week)',
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name='distributionentry',
            name='authorized_representative',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Authorized representative name',
                max_length=200,
            ),
        ),
    ]
