# Generated by Django 6.0.3 on 2026-05-27 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_add_expected_sowing_authorized'),
        ('seed_poll', '0003_finalseed'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionevent',
            name='final_seed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='seed_poll.finalseed'),
        ),
    ]
