# Generated by Django 6.0.3 on 2026-06-03 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0006_distributionevent_final_seed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionbatch',
            name='distribution_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionbatch',
            name='distribution_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_batches_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distributionbatch',
            name='distribution_rejected_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='distributionbatch',
            name='distribution_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='distributionbatch',
            name='distribution_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
