# Generated by Django 6.0.3 on 2026-06-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0007_distributionbatch_distribution_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionentry',
            name='qty_bags',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of seed bags received (decimal allowed, e.g. 0.50)', max_digits=6, null=True),
        ),
    ]
