# Generated by Django 6.0.3 on 2026-03-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(max_length=11, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('AT', 'Agricultural Technician'), ('BRGY', 'Barangay President'), ('FARMER', 'Farmer')], default='FARMER', max_length=10)),
                ('barangay', models.CharField(blank=True, choices=[('Abang', 'Abang'), ('Aliliw', 'Aliliw'), ('Atulinao', 'Atulinao'), ('Ayuti', 'Ayuti'), ('Igang', 'Igang'), ('Kabatete', 'Kabatete'), ('Kakawit', 'Kakawit'), ('Kalangay', 'Kalangay'), ('Kalyaat', 'Kalyaat'), ('Kilib', 'Kilib'), ('Kulapi', 'Kulapi'), ('Mahabang Parang', 'Mahabang Parang'), ('Malupak', 'Malupak'), ('Manasa', 'Manasa'), ('May-It', 'May-It'), ('Nagsinamo', 'Nagsinamo'), ('Nalunao', 'Nalunao'), ('Palola', 'Palola'), ('Piis', 'Piis'), ('Samil', 'Samil'), ('Tiawe', 'Tiawe'), ('Tinamnan', 'Tinamnan')], max_length=50, null=True)),
                ('rsbsa_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
