# Generated by Django 6.0.3 on 2026-03-24 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_status_farmerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalTechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_barangay', models.CharField(choices=[('Abang', 'Abang'), ('Aliliw', 'Aliliw'), ('Atulinao', 'Atulinao'), ('Ayuti', 'Ayuti'), ('Igang', 'Igang'), ('Kabatete', 'Kabatete'), ('Kakawit', 'Kakawit'), ('Kalangay', 'Kalangay'), ('Kalyaat', 'Kalyaat'), ('Kilib', 'Kilib'), ('Kulapi', 'Kulapi'), ('Mahabang Parang', 'Mahabang Parang'), ('Malupak', 'Malupak'), ('Manasa', 'Manasa'), ('May-It', 'May-It'), ('Nagsinamo', 'Nagsinamo'), ('Nalunao', 'Nalunao'), ('Palola', 'Palola'), ('Piis', 'Piis'), ('Samil', 'Samil'), ('Tiawe', 'Tiawe'), ('Tinamnan', 'Tinamnan')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='at_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrgyPresidentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(choices=[('Abang', 'Abang'), ('Aliliw', 'Aliliw'), ('Atulinao', 'Atulinao'), ('Ayuti', 'Ayuti'), ('Igang', 'Igang'), ('Kabatete', 'Kabatete'), ('Kakawit', 'Kakawit'), ('Kalangay', 'Kalangay'), ('Kalyaat', 'Kalyaat'), ('Kilib', 'Kilib'), ('Kulapi', 'Kulapi'), ('Mahabang Parang', 'Mahabang Parang'), ('Malupak', 'Malupak'), ('Manasa', 'Manasa'), ('May-It', 'May-It'), ('Nagsinamo', 'Nagsinamo'), ('Nalunao', 'Nalunao'), ('Palola', 'Palola'), ('Piis', 'Piis'), ('Samil', 'Samil'), ('Tiawe', 'Tiawe'), ('Tinamnan', 'Tinamnan')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bp_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
