# Generated by Django 6.0.3 on 2026-03-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_requested',
            field=models.BooleanField(default=False),
        ),
    ]
