# Generated by Django 6.0.3 on 2026-03-29 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_passwordresetotp_is_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Abang', 'Abang'), ('Aliliw', 'Aliliw'), ('Atulinao', 'Atulinao'), ('Ayuti', 'Ayuti'), ('Igang', 'Igang'), ('Kabatete', 'Kabatete'), ('Kakawit', 'Kakawit'), ('Kalangay', 'Kalangay'), ('Kalyaat', 'Kalyaat'), ('Kilib', 'Kilib'), ('Kulapi', 'Kulapi'), ('Mahabang Parang', 'Mahabang Parang'), ('Malupak', 'Malupak'), ('Manasa', 'Manasa'), ('May-It', 'May-It'), ('Nagsinamo', 'Nagsinamo'), ('Nalunao', 'Nalunao'), ('Palola', 'Palola'), ('Piis', 'Piis'), ('Samil', 'Samil'), ('Tiawe', 'Tiawe'), ('Tinamnan', 'Tinamnan')], max_length=100, unique=True)),
                ('assigned_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barangays', to='accounts.agriculturaltechnicianprofile')),
            ],
            options={
                'verbose_name': 'Barangay',
                'verbose_name_plural': 'Barangays',
                'ordering': ['name'],
            },
        ),
    ]
