# Generated by Django 6.0.3 on 2026-03-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_barangay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_reset_requested',
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
