# Generated by Django 6.0.3 on 2026-05-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_password_reset_requested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agriculturaltechnicianprofile',
            name='assigned_barangay',
        ),
        migrations.RemoveField(
            model_name='brgypresidentprofile',
            name='barangay',
        ),
    ]
