# Generated by Django 6.0.3 on 2026-05-27 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_agriculturaltechnicianprofile_assigned_barangay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='email',
        ),
    ]
