# Generated by Django 6.0.3 on 2026-05-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_farmerprofile_hectares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='hectares',
        ),
    ]
