# Generated by Django 6.0.3 on 2026-05-30 06:04

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_farmerprofile_hectares'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='id_card',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.accounts.models.farmer_id_upload_path,
                validators=[apps.accounts.models.validate_id_card],
            ),
        ),
    ]
