# Generated by Django 6.0.3 on 2026-06-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_farmerprofile_id_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerMasterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsbsa_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('barangay', models.CharField(choices=[('Abang', 'Abang'), ('Aliliw', 'Aliliw'), ('Atulinao', 'Atulinao'), ('Ayuti', 'Ayuti'), ('Igang', 'Igang'), ('Kabatete', 'Kabatete'), ('Kakawit', 'Kakawit'), ('Kalangay', 'Kalangay'), ('Kalyaat', 'Kalyaat'), ('Kilib', 'Kilib'), ('Kulapi', 'Kulapi'), ('Mahabang Parang', 'Mahabang Parang'), ('Malupak', 'Malupak'), ('Manasa', 'Manasa'), ('May-It', 'May-It'), ('Nagsinamo', 'Nagsinamo'), ('Nalunao', 'Nalunao'), ('Palola', 'Palola'), ('Piis', 'Piis'), ('Samil', 'Samil'), ('Tiawe', 'Tiawe'), ('Tinamnan', 'Tinamnan')], max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=11, null=True)),
                ('hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
