# Generated by Django 6.0.3 on 2026-08-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_farmermasterrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='date_deceased',
            field=models.DateField(blank=True, help_text='Date farmer was recorded as deceased', null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='is_deceased',
            field=models.BooleanField(default=False, help_text='Marks farmer as deceased for record-keeping'),
        ),
    ]
