# Generated by Django 6.0.3 on 2026-09-01 13:55

import apps.accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_farmerprofile_date_deceased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='predecessor',
            field=models.ForeignKey(blank=True, help_text='Deceased farmer that this farmer is claiming to succeed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='accounts.farmerprofile'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='predecessor_relationship',
            field=models.CharField(blank=True, choices=[('SON', 'Son'), ('DAUGHTER', 'Daughter'), ('SPOUSE', 'Spouse'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('OTHER_RELATIVE', 'Other Relative'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='succession_document',
            field=models.FileField(blank=True, null=True, upload_to=apps.accounts.models.succession_document_upload_path, validators=[apps.accounts.models.validate_succession_document]),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='succession_document_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='succession_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
    ]
