# Generated by Django 6.0.3 on 2026-09-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_farmerprofile_predecessor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturaltechnicianprofile',
            name='archived_barangays_snapshot',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanently_archived',
            field=models.BooleanField(default=False),
        ),
    ]
