# Generated by Django 6.0.3 on 2026-09-15 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_agriculturaltechnicianprofile_archived_barangays_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=200)),
                ('actor_role', models.CharField(blank=True, max_length=10)),
                ('action', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=50)),
                ('activity_type', models.CharField(choices=[('DATA_CHANGE', 'Data Changes'), ('SECURITY', 'Security'), ('USER_MANAGEMENT', 'User Management'), ('WORKFLOW', 'Workflow'), ('SYSTEM_CONFIGURATION', 'System Configuration'), ('SYSTEM_ACTIVITY', 'System Activity')], default='SYSTEM_ACTIVITY', max_length=30)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'action'], name='accounts_au_module_394f59_idx'), models.Index(fields=['activity_type'], name='accounts_au_activit_1f0be4_idx'), models.Index(fields=['created_at'], name='accounts_au_created_606b86_idx'), models.Index(fields=['actor'], name='accounts_au_actor_i_4b63b5_idx')],
            },
        ),
    ]
