# Generated by Django 6.0.3 on 2026-04-13 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seed_poll', '0003_finalseed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('WET', 'Wet Season'), ('DRY', 'Dry Season')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('REGION', 'Region (NRP/RFO)'), ('PHILRICE', 'PhilRice (RCEF)')], max_length=20)),
                ('total_bags', models.PositiveIntegerField()),
                ('delivery_date', models.DateField()),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encoded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_deliveries', to=settings.AUTH_USER_MODEL)),
                ('seed_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='seed_poll.seedtype')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='seed_poll.seedvariety')),
            ],
            options={
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrgyAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(max_length=100)),
                ('allocated_bags', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Pickup'), ('CONFIRMED', 'Confirmed Received')], default='PENDING', max_length=20)),
                ('date_allocated', models.DateField(auto_now_add=True)),
                ('date_confirmed', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_allocations', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='seed_inventory.seeddelivery')),
            ],
            options={
                'ordering': ['barangay'],
                'unique_together': {('delivery', 'barangay')},
            },
        ),
        migrations.CreateModel(
            name='SeedDeliveryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Delivery Created'), ('UPDATED', 'Delivery Updated'), ('ALLOCATED', 'Bags Allocated to Barangay'), ('CONFIRMED', 'Pickup Confirmed by BRGY'), ('DELETED', 'Delivery Deleted')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='seed_inventory.brgyallocation')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='seed_inventory.seeddelivery')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
