# Generated by Django 6.0.3 on 2026-05-27 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed_inventory', '0001_initial'),
        ('seed_poll', '0003_finalseed'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeddelivery',
            name='final_seed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='seed_poll.finalseed'),
        ),
    ]
