# Generated by Django 6.0.3 on 2026-06-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed_inventory', '0002_seeddelivery_final_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeddelivery',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DELIVERED', 'Delivered')], default='SCHEDULED', max_length=20),
        ),
    ]
