# Generated by Django 6.0.3 on 2026-06-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed_inventory', '0003_seeddelivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brgyallocation',
            name='allocated_bags',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
