# Generated by Django 6.0.3 on 2026-06-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed_inventory', '0004_alter_brgyallocation_allocated_bags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_type_db_id', models.IntegerField(blank=True, null=True)),
                ('seed_type_name', models.CharField(max_length=100)),
                ('variety_id', models.IntegerField(blank=True, null=True)),
                ('variety_name', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(choices=[('WET', 'Wet Season'), ('DRY', 'Dry Season')], max_length=3)),
                ('year', models.PositiveIntegerField()),
                ('total_bags', models.PositiveIntegerField(default=0)),
                ('delivery_date', models.DateField()),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DELIVERED', 'Delivered')], default='SCHEDULED', max_length=20)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='seed_inventory.deliveryschedule')),
            ],
            options={
                'ordering': ['season', 'year'],
            },
        ),
    ]
