# Generated by Django 6.0.3 on 2026-04-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announced_date',
            field=models.DateField(blank=True, help_text='Display date shown to users. Defaults to creation date if empty.', null=True),
        ),
    ]
