# Generated by Django 6.0.3 on 2026-05-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_announced_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='action_title',
            field=models.CharField(blank=True, default='', help_text='Optional button text for an action users should take.', max_length=140),
        ),
        migrations.AddField(
            model_name='announcement',
            name='action_url',
            field=models.CharField(blank=True, default='', help_text='Optional internal path or URL for the action button.', max_length=250),
        ),
    ]
