# Generated by Django 6.0.3 on 2026-06-03 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seed_poll', '0003_finalseed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPhaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(max_length=100)),
                ('crop_phase', models.CharField(choices=[('DISTRIBUTION', 'Seed Distribution'), ('ESTABLISHMENT', 'Crop Establishment'), ('TILLERING', 'Tillering'), ('FLOWERING', 'Flowering'), ('RIPENING', 'Ripening'), ('HARVESTING', 'Harvesting')], max_length=20)),
                ('date_recorded', models.DateField()),
                ('encoded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_phase_records', to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(help_text='The season this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='crop_phase_records', to='seed_poll.poll')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_phases_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crop Phase Record',
                'ordering': ['-encoded_at'],
                'unique_together': {('poll', 'farmer')},
            },
        ),
    ]
