# Generated by Django 6.0.3 on 2026-04-15 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('HYBRID_MASTERLIST', 'Hybrid Masterlist'), ('PHILRICE_MASTERLIST', 'PhilRice Masterlist'), ('SEED_DISTRIBUTION', 'Seed Distribution'), ('FARMER_REGISTRATION', 'Farmer Registration'), ('PLANTING_ACCOMPLISHMENT', 'Planting Accomplishment'), ('HARVESTING_ACCOMPLISHMENT', 'Harvesting Accomplishment')], max_length=40)),
                ('season', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Log',
                'ordering': ['-generated_at'],
            },
        ),
    ]
