# Generated by Django 6.0.3 on 2026-05-24 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(db_index=True, max_length=100)),
                ('label', models.CharField(blank=True, default='Main Farm', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('area_ha', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('land_type', models.CharField(blank=True, default='Irrigated', max_length=50)),
                ('boundary_points', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'FARMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='farm_plots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['barangay', 'farmer__last_name'],
            },
        ),
    ]
