# Generated by Django 6.0.3 on 2026-04-04 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HYBRID', 'Hybrid'), ('INBRED', 'Inbred')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Wet Season 2026 Seed Preference Poll"', max_length=200)),
                ('season', models.CharField(choices=[('WET', 'Wet Season'), ('DRY', 'Dry Season')], max_length=3)),
                ('year', models.PositiveIntegerField(help_text='e.g. 2026')),
                ('end_date', models.DateTimeField(help_text='Poll automatically closes after this date and time')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeedVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('seed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='seed_poll.seedtype')),
            ],
            options={
                'verbose_name_plural': 'Seed Varieties',
                'ordering': ['seed_type', 'name'],
                'unique_together': {('seed_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='seed_poll.poll')),
                ('hybrid_choice', models.ForeignKey(limit_choices_to={'seed_type__name': 'HYBRID'}, on_delete=django.db.models.deletion.PROTECT, related_name='hybrid_votes', to='seed_poll.seedvariety')),
                ('inbred_choice', models.ForeignKey(limit_choices_to={'seed_type__name': 'INBRED'}, on_delete=django.db.models.deletion.PROTECT, related_name='inbred_votes', to='seed_poll.seedvariety')),
            ],
            options={
                'ordering': ['-voted_at'],
                'unique_together': {('poll', 'farmer')},
            },
        ),
    ]
