# Generated by Django 6.0.3 on 2026-04-05 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed_poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seedtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='pollvote',
            name='hybrid_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hybrid_votes', to='seed_poll.seedvariety'),
        ),
        migrations.AlterField(
            model_name='pollvote',
            name='inbred_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbred_votes', to='seed_poll.seedvariety'),
        ),
        migrations.AlterField(
            model_name='seedtype',
            name='name',
            field=models.CharField(help_text='e.g. Hybrid, Inbred, Own Seed, Certified', max_length=100, unique=True),
        ),
    ]
