# Generated by Django 6.0.3 on 2026-04-11 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed_poll', '0002_alter_seedtype_options_alter_pollvote_hybrid_choice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('WET', 'Wet Season'), ('DRY', 'Dry Season')], max_length=10)),
                ('year', models.IntegerField()),
                ('source', models.CharField(choices=[('REGION', 'Region'), ('PHILRICE', 'PhilRice')], default='REGION', max_length=20)),
                ('confirmed_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_seeds', to=settings.AUTH_USER_MODEL)),
                ('seed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_seeds', to='seed_poll.seedtype')),
                ('varieties', models.ManyToManyField(blank=True, related_name='final_selections', to='seed_poll.seedvariety')),
            ],
            options={
                'ordering': ['-year', 'seed_type__name'],
                'unique_together': {('season', 'year', 'seed_type')},
            },
        ),
    ]
